CREATE DATABASE CINEPRUEBA
		CONTAINMENT = NONE
		ON  PRIMARY 
		( NAME = N'CINEPRUEBA', FILENAME = N'C:\BASES DE DATOS SQL\CINEPRUEBA.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
		LOG ON 
		( NAME = N'CINEPRUEBA_log', FILENAME = N'C:\BASES DE DATOS SQL\CINEPRUEBA_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
		
USE CINEPRUEBA;

CREATE TABLE TIPO_CLIENTE
(
		ID_TIPO_CLIENTE INT NOT NULL IDENTITY (1,1),
		DESCRIPCION VARCHAR(50) NOT NULL,
		PRIMARY KEY( ID_TIPO_CLIENTE )
);

CREATE TABLE CLIENTE 
(
		ID_CLIENTE INT NOT NULL IDENTITY (1,1),
		PRIMER_NOMBRE VARCHAR(20) NULL,
		SEGUNDO_NOMBRE VARCHAR(20) NULL,
		APATERNO VARCHAR(20) NULL,
		AMATERNO VARCHAR(20) NULL,
		ID_TIPO_CLIENTE INT NULL,
		ID_TARJETA_CLUB INT NULL,
		FECHA_NACIMIENTO DATE NULL,
		EMAIL VARCHAR(50) NULL,
		PRIMARY KEY( ID_CLIENTE )
);
 
-- NORMAL,3D,4D,IMAX,VIP
CREATE TABLE TIPO_SALA (
		ID_TIPO_SALA INT NOT NULL IDENTITY (1,1),
		DESCRIPCION VARCHAR(50) NOT NULL,
		PRIMARY KEY( ID_TIPO_SALA )
);
 
--NUMERO DE SALA, 1, 2, 3, 4, 5...
CREATE TABLE SALA ( 
		ID_SALA INT NOT NULL IDENTITY (1,1),
		ID_TIPO_SALA INT NOT NULL,
		PRIMARY KEY( ID_SALA ),
		INDEX ID_TIPO_SALA_idx ( ID_TIPO_SALA ASC),
		CONSTRAINT TIPO_SALA_SALA 
				FOREIGN KEY( ID_TIPO_SALA )    
				REFERENCES TIPO_SALA ( ID_TIPO_SALA )
				ON DELETE NO ACTION
				ON UPDATE NO ACTION
);
 
 --DRAMA, COMEDIA, SUSPENSO, TERROR...
CREATE TABLE GENERO (
			ID_GENERO INT NOT NULL IDENTITY (1,1),
			DESCRIPCION VARCHAR(20)NOT NULL,
			PRIMARY KEY( ID_GENERO )
);
 
 -- AA, A, B, C
CREATE TABLE CLASIFICACION (
		ID_CLASIFICACION INT NOT NULL IDENTITY (1,1),
		DESCRIPCION VARCHAR(5)NOT NULL,
		PRIMARY KEY( ID_CLASIFICACION )
);
 
 CREATE TABLE PELICULA (
		ID_PELICULA INT NOT NULL IDENTITY (1,1),
		NOMBRE VARCHAR(100)NOT NULL,
		ID_GENERO INT NOT NULL,
		ID_CLASIFICACION INT NOT NULL,
		DURACION INT NOT NULL,
		PRIMARY KEY( ID_PELICULA ),
		INDEX ID_GENERO_idx ( ID_GENERO ASC),
		INDEX ID_CLASIFICACION_idx ( ID_CLASIFICACION ASC),
		CONSTRAINT PELICULA_GENERO 
				FOREIGN KEY( ID_GENERO )
				REFERENCES GENERO ( ID_GENERO )
				ON DELETE NO ACTION
				ON UPDATE NO ACTION,
		CONSTRAINT PELICULA_CLASIFICACION 
				FOREIGN KEY( ID_CLASIFICACION )
				REFERENCES CLASIFICACION ( ID_CLASIFICACION )
				ON DELETE NO ACTION
				ON UPDATE NO ACTION
);
 

CREATE TABLE IDIOMA (
		ID_IDIOMA INT NOT NULL IDENTITY (1,1),
		DESCRIPCION VARCHAR(45) NOT NULL,
		PRIMARY KEY( ID_IDIOMA )
);
 

CREATE TABLE FUNCION (
		ID_FUNCION INT NOT NULL IDENTITY (1,1),
		ID_PELICULA INT NOT NULL,
		ID_IDIOMA INT NOT NULL,
		INDEX ID_IDIOMA_idx ( ID_IDIOMA ASC),
		PRIMARY KEY( ID_FUNCION ),
		INDEX ID_PELICULA_idx ( ID_PELICULA ASC),
		CONSTRAINT FUNCION_IDIOMA 
				FOREIGN KEY( ID_IDIOMA )
				REFERENCES IDIOMA ( ID_IDIOMA )
				ON DELETE NO ACTION
				ON UPDATE NO ACTION,
		CONSTRAINT FUNCION_PELICULA 
				FOREIGN KEY( ID_PELICULA )
				REFERENCES PELICULA ( ID_PELICULA )
				ON DELETE NO ACTION
				ON UPDATE NO ACTION
);
 
 
CREATE TABLE PELICULA_SALA (
		ID_FUNCION INT NOT NULL,
		ID_SALA INT NOT NULL,
		FECHA_ENTRADA DATE NOT NULL,
		FECHA_SALIDA DATE NULL,
		INDEX ID_SALA_idx ( ID_SALA ASC),
		INDEX ID_FUNCION_idx ( ID_FUNCION ASC),
		CONSTRAINT PELICULA_SALA_SALA
				FOREIGN KEY( ID_SALA )
				REFERENCES SALA ( ID_SALA )
				ON DELETE NO ACTION
				ON UPDATE NO ACTION,
		CONSTRAINT PELICULA_SALA_FUNCION 
				FOREIGN KEY( ID_FUNCION )
				REFERENCES FUNCION ( ID_FUNCION )
				ON DELETE NO ACTION
				ON UPDATE NO ACTION
);
 
 
CREATE TABLE BOLETO (
		ID_BOLETO INT NOT NULL IDENTITY (1,1),
		FECHA DATE NOT NULL,
		ID_CLIENTE INT NOT NULL,
		ID_FUNCION INT NOT NULL,
		ID_SALA INT NOT NULL,
		PRIMARY KEY( ID_BOLETO ),
		INDEX ID_CLIENTE_idx ( ID_CLIENTE ASC),
		INDEX ID_SALA_idx ( ID_SALA ASC),
		INDEX ID_FUNCION_idx ( ID_FUNCION ASC),
		CONSTRAINT BOLETO_CLIENTE 
				FOREIGN KEY( ID_CLIENTE )
				REFERENCES CLIENTE ( ID_CLIENTE )
				ON DELETE NO ACTION
				ON UPDATE NO ACTION
);


